server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: HOSPITAL-MANAGEMENT-SYSTEM
          uri: lb://HOSPITAL-MANAGEMENT-SYSTEM
          predicates:
            - Path=/hiring/doctor,/register/patient,/get/patient/{patientId},/pathology/test,/pathology/test/{testId},create/building,/admit/patient

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761
